short_name = "redot"
name = "Redot Engine"
major = 26
minor = 3
patch = 0
status = "rc"
status_version = 1
module_config = ""
website = "https://redotengine.org"
docs = "latest"
godot_major = 4
godot_minor = 5
godot_patch = 2
godot_status = "stable"
